quarkus.application.name=microservico-analise-inteligente
quarkus.http.port=8090

quarkus.http.host=0.0.0.0
# Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Configuração do REST Client apontando para o seu BFF
# Em produção, você pode usar variável de ambiente: ${URL_BFF:http://microservico-radares-bff:8081}
#quarkus.rest-client.bff-api.url=http://localhost:8081
quarkus.rest-client.bff-api.url=${BFF_URL:http://localhost:8081}

# Aumenta o tempo limite de conexão e leitura para o BFF (para pesquisas pesadas)
quarkus.rest-client.bff-api.read-timeout=120000
quarkus.rest-client.bff-api.connect-timeout=30000

# Log
quarkus.log.level=INFO

# URL do seu Eureka Server (ajuste se estiver usando o nome do container no Docker)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


# CONFIGURAÇÕES DO CLIENTE EUREKA (REST CLIENT)
# A URL base para o nosso EurekaRestClient
quarkus.rest-client.eureka-api.url=${EUREKA_URL:http://localhost:8761/eureka}

# (Opcional) Aumenta o timeout para evitar falhas se o Eureka estiver lento a iniciar
quarkus.rest-client.eureka-api.connect-timeout=5000
quarkus.rest-client.eureka-api.read-timeout=5000